### PR TITLE
fix: wrong date bug in schedule page

### PR DESCRIPTION
**Pull request by diogogmatos**

### CODE REVIEW

**Comment by diogogmatos** [comment]
I guess we will only know if this worked tomorrow 🫠

**Review by ruilopesm — APPROVED** [review]

**Comment by diogogmatos** [comment]
@ruilopesm not sure this works yet, because the deploy preview was built today and the bug only happens when the deployed version was built on a different day then the current date. The highlighted day in the schedule page is the day when the app was built. For example, right now Calendarium is highlighting Thursday has the current day even though it is Friday, because the last deploy of the site was yesterday.

**Comment by ruilopesm** [comment]
@diogogmatos Let's wait till tomorrow, then 😁

**Comment by ruilopesm** [comment]
@diogogmatos I just checked calendarium on production and for me, on my mobile, it's correct (highlighting friday). Don't know if this is happening to just some people. In fact, yesterday it was happening on my computer 😅

**Comment by diogogmatos** [comment]
> @diogogmatos I just checked calendarium on production and for me, on my mobile, it's correct (highlighting friday). Don't know if this is happening to just some people. In fact, yesterday it was happening on my computer 😅

@ruilopesm it only happens when you open the page directly in /schedule or refresh the page while in /schedule. If you open in / and then change to /schedule it works correctly. (I know very weird)

**Comment by ruilopesm** [comment]
@diogogmatos I can reproduce it now. What a strange bug 💀

**Comment by joaodiaslobo** [comment]
@diogogmatos @ruilopesm Unfortunately, I don't think this fixed the bug. 🥲 
I think we have a very odd one in our hands :shipit:

**Comment by diogogmatos** [comment]
Fixed for now in #233

**Pull request closed without merging**
