### PR TITLE
Improve styling & code organization

### PR DESCRIPTION
**Pull request by sassypocoyo**
Made significant improvements to the styling of the Navbar and the FeedbackForm, enabling a cleaner and more organized view on mobile devices especially. Also imported some fonts from Google Fonts for a more cohesive experience between devices.

While I was on it also made some improvements to the organization of the code, moving some components to folders.

**Desktop view:**

image

**Mobile view:**

**Footer (Desktop):**

image

**Footer (Mobile):**

image

### CODE REVIEW

**Review by RuiL1904 — COMMENTED** [review]
Unlike you, I don't get any margin on the footer. Can you see this? 🙏🏼

image

**Comment by sassypocoyo** [comment]
> Unlike you, I don't get any margin on the footer. Can you see this? 🙏🏼
> 
> image

Turns out it was Google Chrome being a b*tch, literally any other browser renders it correctly xD. Anyway, problem solved, thanks! :pray:

**Review by RuiL1904 — APPROVED** [review]
Great work! 🚀

**Review by ruioliveira02 — COMMENTED** [review]
image
I have this issue, which was solved in #39 and is coming back. Not happening in master.

**Review by ruioliveira02 — APPROVED** [review]

**Pull request merged**
