### PR TITLE
Remove "Extract to PDF" 

### PR DESCRIPTION
**Pull request by MarioRodrigues10**

### CODE REVIEW

**Comment by ruioliveira02** [comment]
Are we really doing this? I think it is a nice feature to have

**Comment by MarioRodrigues10** [comment]
> Are we really doing this? I think it is a nice feature to have

I think it's an unnecessary feature to have. I put myself in the user perspective. What would I do? Just press 2 buttons and take a screenshot instead of downloading a pdf

**Comment by ruioliveira02** [comment]
If anything we remove it on mobile. For desktop i think it is easier to just export to pdf rather than having to take a screenshot. But let's wait for more feedback @RuiL1904 @EnzoVieira @tiago-bacelar

**Comment by EnzoVieira** [comment]
> I agree with @ruioliveira02. Even if we can "just press 2 buttons", having more options for the user is good. Anyway, this feature is, currently, not working as intended and I think we should fix instead of removing it.

I agree in giving more options, some users can prefer to use pdf for organizations purpose (like me, I use to save my classes schedule in cloud as PDF), so we can remove temporarily the feature only in mobile to fix it.

**Pull request closed without merging**
