### PR TITLE
Add 2y2s events & Improve shift view

### PR DESCRIPTION
**Pull request by diogogmatos**
Added all the events known so far for 2nd year 2nd semester and made some improvements to the shift view on Schedule page.
Now the shift title will be composed of the class acronym and the full class title will only be shown on the Modal.

- Add 2year 2sem events
- Improve Schedule view

### CODE REVIEW

**Review by MarioRodrigues10 — COMMENTED** [review]
Let's wait for the 2nd semester events for all grades before we merge this PR

**Comment by diogogmatos** [comment]
> Let's wait for the 2nd semester events for all grades before we merge this PR

i don't think there's a problem with adding the events of just the 2nd year instead of adding all of them at once. im adding the 2nd years events on this PR, someone else can add the 3rd year events, etc. and we can deploy only after we have all of them, if you think that's better.

**Comment by MarioRodrigues10** [comment]
> > Let's wait for the 2nd semester events for all grades before we merge this PR
> 
> i don't think there's a problem with adding the events of just the 2nd year instead of adding all of them at once. im adding the 2nd years events on this PR, someone else can add the 3rd year events, etc. and we can deploy only after we have all of them, if you think that's better.

To ensure that everything remains within the same context, it would be better to consolidate all the changes into a single PR

**Comment by RuiL1904** [comment]
I disagree with you, @MarioRodrigues10. I think you're being too strict. The major objective of the platform is to deliver information on-the-fly, providing the best we can to our students.

**Comment by MarioRodrigues10** [comment]
> I disagree with you, @MarioRodrigues10. I think you're being too strict. The major objective of the platform is to deliver information on-the-fly, providing the best we can to our students.

Well I understand your perspective, I respectfully disagree. In my opinion, it would be helpful to provide students with the information as soon as possible to ensure they have enough time to prepare and plan accordingly. However, waiting a week to gather all the necessary information i think won't be harmful for the students.

**Comment by EnzoVieira** [comment]
I suggest we open an discution about this topic, because I think it's better for our students we give them information on-the-fly accordingly with what Rui said. Also, I don't see any reason to wait and give all the information at once, neither the university do that. We can continuously delivery them information as we get them.

@MarioRodrigues10 @RuiL1904

**Pull request merged**
