### PR TITLE
Improve Typescript

### PR DESCRIPTION
**Pull request by diogogmatos**
Improved the typescript in the `Notifications` component and removed some left-over unnecessary code.

- improve typescript
- remove unnecessary code

### CODE REVIEW

**Review by MarioRodrigues10 — APPROVED** [review]

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
Please make sure the CI passes, the code was looking fine.

**Comment by diogogmatos** [comment]
@MarioRodrigues10 I think it's a Netlify error, the project is showing no lint errors locally and is building fine with `npm run build` as well as running with `npm run dev`. I can't get Netlify to re-run the jobs, can you do that? Thank you :pray:

**Comment by diogogmatos** [comment]
@MarioRodrigues10 Forced Netlify to re-run its jobs by making a useless commit, it's passing now ;) It must have been some kind of bug.

**Review by MarioRodrigues10 — APPROVED** [review]
:rocket:

**Pull request merged**
